# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Wed, 10 Jan 2024 20:14:17 +0000
*               @ALL          1
*               @user         8
