<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: yvonne
 * Date: Fri, 12 Jan 2024 21:48:47 +0100
 */

$conf['title'] = 'Data Physicalization Wiki';
$conf['start'] = 'data_physicalization';
$conf['template'] = '20cones';
$conf['showuseras'] = 'username';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['locktime'] = 60*60;
$conf['subscribers'] = 1;
$conf['userewrite'] = '1';
$conf['useslash'] = 1;
$conf['tpl']['20cones']['20cones_htmltopbar'] = 0;
