# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Wed, 10 Jan 2024 20:14:17 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

yvonne:$2y$10$COzWCRCOTChZnCeHRJZmLuEsscNOa9keyIvutTmpzMFa86CLazQYu:Yvonne:info@dataphys.org:admin,user
