name: Deploy dataphys wiki

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.OVH_SSH_KEY }}
        SSH_PASSPHRASE: ${{ secrets.OVH_SSH_PASSPHRASE }}
        OVH_SSH_HOST_KEY: ${{ secrets.OVH_SSH_HOST_KEY }}
        OVH_USER: ${{ secrets.OVH_USER }}
        OVH_HOST: ${{ secrets.OVH_HOST }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519

        # Add the OVH server to known_hosts to avoid host key verification failure
        echo "$OVH_SSH_HOST_KEY" >> ~/.ssh/known_hosts

        # Start the SSH agent and add the key with the passphrase
        eval "$(ssh-agent -s)"
        echo "$SSH_PASSPHRASE" | ssh-add ~/.ssh/id_ed25519

        # Verify SSH connection
        ssh -o StrictHostKeyChecking=yes $OVH_USER@$OVH_HOST "echo 'SSH connection successful'"

    - name: Deploy to OVH
      env:
        OVH_USER: ${{ secrets.OVH_USER }}
        OVH_HOST: ${{ secrets.OVH_HOST }}
        OVH_PATH: ${{ secrets.OVH_PATH }}
      run: |
        rsync -avz --delete -e "ssh -o StrictHostKeyChecking=yes" . $OVH_USER@$OVH_HOST:$OVH_PATH
